Lab1_Notas/Lab1_Notas/Models/Acciones.cs
namespace Lab1_Notas.Models
{
    public class Acciones
    {
        public string nombre { get; set; }
        public Double lab1 { get; set; }
        public Double lap2 { get; set; }
        public Double lap3 { get; set; }
        public Double par1 { get; set; }
        public Double par2 { get; set; }
        public Double par3 { get; set; }
    }
}

Lab1_Notas/Lab1_Notas/Models/ErrorViewModel.cs
namespace Lab1_Notas.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Lab1_Notas/Lab1_Notas/Controllers/HomeController.cs
using Lab1_Notas.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Lab1_Notas.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        public IActionResult index_()
        {
            return View();
        }
    }
}

Lab1_Notas/Lab1_Notas/Controllers/NotasController.cs
using Lab1_Notas.Bussines;
using Lab1_Notas.Models;
using Microsoft.AspNetCore.Mvc;

namespace Lab1_Notas.Controllers
{
    public class NotasController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult index_(Acciones acciones )
        {

            Operaciones op = new Operaciones();
            double resultado = op.index(acciones);
            
            ViewBag.variableaenviar = resultado;
            
            return View();
        }
       
    }
}

Lab1_Notas/Lab1_Notas/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Lab1_Notas/Lab1_Notas/Views/Notas/index_.cshtml
@model Lab1_Notas.Models.Acciones


@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1 class="titulo" >Registro De Notas</h1>

<div class="color">
<form asp-controller="Notas" asp-action="index_"> 
    <div class="card"> 
<label>Nombre</label>
 <input type="text" asp-for="nombre"  placeholder="Nombre"  class="form-control" />
 <hr />


 <label>Laboratorio 1</label>
 <input type="number" asp-for="lab1" placeholder="Ingresa Nota"  class="form-control" min="0" max="10"/>

  <label>Parcial 1</label>
 <input type="number" asp-for="par1" placeholder="Ingresa Nota"   class="form-control" min="0" max="10"/>
   <hr />
    <label>laboratorio 2</label>
 <input type="number" asp-for="lap2" placeholder="Ingresa Nota"  class="form-control" min="0" max="10"/>
  <hr />
  <label>Parcial 2</label>
 <input type="number" asp-for="par2" placeholder="Ingresa Nota"   class="form-control" min="0" max="10"/>
   <hr />
   <label> Laboratorio 3</label>
 <input type="number" asp-for="lap3" placeholder="Ingresa Nota"  class="form-control" min="0" max="10"/>
 <hr />

   <label>Parcial 3</label>
 <input type="number" asp-for="par3" placeholder="Ingresa Nota"  class="form-control" min="0" max="10"/>
  <hr />
 

<button  class="btn btn-danger">Promedio</button>
<label> resultado</label>
<textarea class="area" >@ViewBag.variableaenviar</textarea>


</div>
</form>

</div>

Lab1_Notas/Lab1_Notas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lab1_Notas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Lab1_Notas.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Lab1_Notas</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Lab1_Notas - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>